prompt --application/pages/page_00007
begin
--   Manifest
--     PAGE: 00007
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.05.31'
,p_release=>'24.1.5'
,p_default_workspace_id=>47256484443582396331
,p_default_application_id=>146762
,p_default_id_offset=>0
,p_default_owner=>'WKSP_MARWORK'
);
wwv_flow_imp_page.create_page(
 p_id=>7
,p_name=>unistr('Extens\00E3o')
,p_alias=>unistr('EXTENS\00C3O1')
,p_step_title=>unistr('Extens\00E3o')
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_help_text=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<p>To find data enter a search term into the search dialog, or click on the column headings to limit the records returned.</p>',
'',
'<p>You can perform numerous functions by clicking the <strong>Actions</strong> button. This includes selecting the columns that are displayed / hidden and their display sequence, plus numerous data and format functions.  You can also define additiona'
||'l views of the data using the chart, group by, and pivot options.</p>',
'',
'<p>If you want to save your customizations select report, or click download to unload the data. Enter you email address and time frame under subscription to be sent the data on a regular basis.<p>',
'',
'<p>For additional information click Help at the bottom of the Actions menu.</p> ',
'',
'<p>Click the <strong>Reset</strong> button to reset the interactive report back to the default settings.</p>'))
,p_page_component_map=>'18'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(84074889648700940492)
,p_plug_name=>unistr('Extens\00E3oes')
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(84074632742269939940)
,p_plug_display_sequence=>10
,p_query_type=>'TABLE'
,p_query_table=>unistr('EXTENS\00C3O')
,p_include_rowid_column=>false
,p_plug_source_type=>'NATIVE_IR'
,p_prn_page_header=>unistr('Extens\00E3o')
);
wwv_flow_imp_page.create_worksheet(
 p_id=>wwv_flow_imp.id(84074889720762940492)
,p_name=>unistr('Extens\00E3o')
,p_max_row_count_message=>'The maximum row count for this report is #MAX_ROW_COUNT# rows.  Please apply a filter to reduce the number of records in your query.'
,p_no_data_found_message=>'No data found.'
,p_allow_save_rpt_public=>'Y'
,p_pagination_type=>'ROWS_X_TO_Y'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'N'
,p_show_notify=>'Y'
,p_download_formats=>'CSV:HTML:XLSX:PDF'
,p_enable_mail_download=>'Y'
,p_owner=>'MARCELABTG@GMAIL.COM'
,p_internal_uid=>84074889720762940492
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(84074890428920940495)
,p_db_column_name=>'ID'
,p_display_order=>0
,p_is_primary_key=>'Y'
,p_column_identifier=>'A'
,p_column_label=>'ID'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN_ESCAPE_SC'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(84074890854009940496)
,p_db_column_name=>'CAMPUS'
,p_display_order=>2
,p_column_identifier=>'B'
,p_column_label=>'Campus'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(84074891201923940496)
,p_db_column_name=>'ANO_DO_EDITAL'
,p_display_order=>3
,p_column_identifier=>'C'
,p_column_label=>'Ano Do Edital'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_format_mask=>'999G999G999G999G999G999G999G999G999G990'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(84074891617661940496)
,p_db_column_name=>unistr('T\00CDTULO_DO_PROJETO')
,p_display_order=>4
,p_column_identifier=>'D'
,p_column_label=>unistr('T\00EDtulo Do Projeto')
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(84074892043820940496)
,p_db_column_name=>'OBJETIVO'
,p_display_order=>5
,p_column_identifier=>'E'
,p_column_label=>'Objetivo'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(84074892449345940497)
,p_db_column_name=>'COORDENADOR_A____DO_PROJETO_DE___PESQUISA'
,p_display_order=>6
,p_column_identifier=>'F'
,p_column_label=>'Coordenador A Do Projeto De Pesquisa'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(84074892822794940497)
,p_db_column_name=>'RESULTADOS_OBTIDOS_E_TRABALHOS_PUBLICADOS'
,p_display_order=>7
,p_column_identifier=>'G'
,p_column_label=>'Resultados Obtidos E Trabalhos Publicados'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(84074893244398940497)
,p_db_column_name=>'FONTE'
,p_display_order=>8
,p_column_identifier=>'H'
,p_column_label=>'Fonte'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_column_alignment=>'CENTER'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_rpt(
 p_id=>wwv_flow_imp.id(84074916553665940520)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'840749166'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_report_columns=>unistr('CAMPUS:ANO_DO_EDITAL:T\00CDTULO_DO_PROJETO:OBJETIVO:COORDENADOR_A____DO_PROJETO_DE___PESQUISA:RESULTADOS_OBTIDOS_E_TRABALHOS_PUBLICADOS:FONTE')
,p_sort_column_1=>'CAMPUS'
,p_sort_direction_1=>'ASC'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(84074894349170940498)
,p_plug_name=>'Breadcrumb'
,p_region_template_options=>'#DEFAULT#:t-BreadcrumbRegion--useBreadcrumbTitle'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(84074654987731939949)
,p_plug_display_sequence=>20
,p_plug_display_point=>'REGION_POSITION_01'
,p_menu_id=>wwv_flow_imp.id(84073939242175939898)
,p_plug_source_type=>'NATIVE_BREADCRUMB'
,p_menu_template_id=>wwv_flow_imp.id(84074717884295939978)
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(84074893600896940497)
,p_button_sequence=>10
,p_button_plug_id=>wwv_flow_imp.id(84074889648700940492)
,p_button_name=>'RESET_REPORT'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'t-Button--iconLeft'
,p_button_template_id=>wwv_flow_imp.id(84074716314118939977)
,p_button_image_alt=>'Reset'
,p_button_position=>'RIGHT_OF_IR_SEARCH_BAR'
,p_button_redirect_url=>'f?p=&APP_ID.:7:&APP_SESSION.::&DEBUG.:RR::'
,p_icon_css_classes=>'fa-undo-alt'
);
wwv_flow_imp.component_end;
end;
/
